import { ProjectMember } from '@/types/projectTypes';

export const mockCompanyMembers: ProjectMember[] = [
  {
    id: '1',
    name: 'Olivia Rhye',
    department: '마케팅팀',
    position: '과장',
    phone: '010-1234-5678',
    email: 'olivia.rhye@company.com',
    role: '루트관리자',
    profileImageUrl: '',
  },
  {
    id: '2',
    name: 'John Smith',
    department: '개발팀',
    position: '팀장',
    phone: '010-1234-5679',
    email: 'john.smith@company.com',
    role: '관리자',
    profileImageUrl: '',
  },
  {
    id: '3',
    name: 'Emma Johnson',
    department: '디자인팀',
    position: '시니어',
    phone: '010-1234-5680',
    email: 'emma.johnson@company.com',
    role: '일반',
    profileImageUrl: '',
  },
  {
    id: '4',
    name: 'Michael Brown',
    department: '기획팀',
    position: '주임',
    phone: '010-1234-5681',
    email: 'michael.brown@company.com',
    role: '일반',
    profileImageUrl: '',
  },
  {
    id: '5',
    name: 'Sarah Davis',
    department: '마케팅팀',
    position: '사원',
    phone: '010-1234-5682',
    email: 'sarah.davis@company.com',
    role: '일반',
    profileImageUrl: '',
  },
  {
    id: '6',
    name: 'David Wilson',
    department: '개발팀',
    position: '시니어',
    phone: '010-1234-5683',
    email: 'david.wilson@company.com',
    role: '관리자',
    profileImageUrl: '',
  },
  {
    id: '7',
    name: 'Lisa Taylor',
    department: '인사팀',
    position: '과장',
    phone: '010-1234-5684',
    email: 'lisa.taylor@company.com',
    role: '관리자',
    profileImageUrl: '',
  },
  {
    id: '8',
    name: 'James Anderson',
    department: '영업팀',
    position: '사원',
    phone: '010-1234-5685',
    email: 'james.anderson@company.com',
    role: '일반',
    profileImageUrl: '',
  },
  {
    id: '9',
    name: 'Jennifer Martinez',
    department: '디자인팀',
    position: '팀장',
    phone: '010-1234-5686',
    email: 'jennifer.martinez@company.com',
    role: '관리자',
    profileImageUrl: '',
  },
  {
    id: '10',
    name: 'Robert Lee',
    department: '기획팀',
    position: '과장',
    phone: '010-1234-5687',
    email: 'robert.lee@company.com',
    role: '일반',
    profileImageUrl: '',
  },
];
