services:

  # backend
  backend:
    build:
      context: ./backend
      target: dev
    container_name: dev-backend
    volumes:
      - ./backend:/app
      - gradle-cache:/home/gradle/.gradle
    working_dir: /app
    command: ./gradlew bootRun
    env_file:
      - ./backend/.env
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DEVTOOLS_REMOTE_SECRET: secretary
    depends_on:
      db:
        condition: service_healthy

  # db
  db:
    image: mysql:8
    container_name: dev-db
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    env_file:
      - ./backend/.env
    environment:
      SPRING_PROFILES_ACTIVE: dev
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

volumes:
  gradle-cache:
  mysql-data: