services:
  # backend
  backend:
    image: ${BACKEND_IMAGE:-ourhour-backend:test}
    container_name: test-backend
    environment:
      SPRING_PROFILES_ACTIVE: test
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  # db
  db:
    image: mysql:8.0
    container_name: test-db
    ports:
      - "3307:3306"
    environment:
      SPRING_PROFILES_ACTIVE: test
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 60s
      retries: 10
    volumes:
      - ./backend/docker/mysql-init:/docker-entrypoint-initdb.d
      - test-mysql-data:/var/lib/mysql

  # redis
  redis:
    image: redis:7-alpine
    container_name: test-redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - test-redis-data:/data
    restart: unless-stopped

  # ai chatbot
  chatbot:
    image: ${CHATBOT_IMAGE:-ourhour-chatbot:test}
    container_name: test-chatbot
    ports:
      - "8000:8000"
    depends_on:
      - db
      - backend
      - redis
    environment:
      - CHATBOT_DATABASE_URL=mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db:3306/${MYSQL_DATABASE}
      - OURHOUR_API_URL=${OURHOUR_API_URL}
      - PYTHON_SERVER_URL=${PYTHON_SERVER_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - PINECONE_INDEX_NAME=${PINECONE_INDEX_NAME}
      - PINECONE_ENVIRONMENT=${PINECONE_ENVIRONMENT}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - ./llm:/app
    networks:
      - default

volumes:
  test-mysql-data:
  test-redis-data: