
services:
  # backend
  backend:
    image: ${BACKEND_IMAGE:-ourhour-backend:prod}
    container_name: release-backend
    environment:
      SPRING_PROFILES_ACTIVE: release
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy

  # db
  db:
    image: mysql:8.0
    container_name: release-db
    ports:
      - "3308:3306"
    environment:
      SPRING_PROFILES_ACTIVE: release
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 60s
      retries: 10
    volumes:
      - ./backend/docker/mysql-init:/docker-entrypoint-initdb.d
      - release-mysql-data:/var/lib/mysql

volumes:
  release-mysql-data: