import { ProjectInfo, ProjectMember } from '@/types/projectTypes';

export const mockProjectMembers: ProjectMember[] = [
  {
    id: '1',
    name: 'Olivia Rhye',
    department: '마케팅팀',
    position: '과장',
    phone: '010-1234-5678',
    email: 'abcd12@naver.com',
    role: '루트관리자',
    profileImageUrl: '',
  },
  {
    id: '2',
    name: 'Olivia Rhye',
    department: '마케팅팀',
    position: '과장',
    phone: '010-1234-5678',
    email: 'abcd12@naver.com',
    role: '관리자',
    profileImageUrl: '',
  },
  {
    id: '3',
    name: 'Olivia Rhye',
    department: '마케팅팀',
    position: '과장',
    phone: '010-1234-5678',
    email: 'abcd12@naver.com',
    role: '일반',
    profileImageUrl: '',
  },
  {
    id: '4',
    name: 'Olivia Rhye',
    department: '마케팅팀',
    position: '과장',
    phone: '010-1234-5678',
    email: 'abcd12@naver.com',
    role: '일반',
    profileImageUrl: '',
  },
  {
    id: '5',
    name: 'Olivia Rhye',
    department: '마케팅팀',
    position: '과장',
    phone: '010-1234-5678',
    email: 'abcd12@naver.com',
    role: '일반',
    profileImageUrl: '',
  },
  {
    id: '6',
    name: 'Olivia Rhye',
    department: '마케팅팀',
    position: '과장',
    phone: '010-1234-5678',
    email: 'abcd12@naver.com',
    role: '관리자',
    profileImageUrl: '',
  },
];

export const mockProjectInfo: ProjectInfo = {
  id: 'm5gr84i9',
  name: '개발 프로젝트명1',
  description: '프로젝트 설명 입니다...',
  startDate: '2025-12-11',
  endDate: '2025-12-30',
  status: '진행중',
  participants: mockProjectMembers,
};
