global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'backend'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ["backend:8080"]

  # Node Exporter 수집 설정
  - job_name: 'node-exporter'
    static_configs:
      - targets: [ 'node-exporter:9100' ]

  # MySQL Exporter 수집 설정
  - job_name: 'mysqld-exporter'
    static_configs:
      - targets: [ 'mysqld-exporter:9104' ]