spring:
  # JPA 관련 설정
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  # flywqy 관련 설정
  flyway:
    enabled: true
    baseline-on-migrate: true

# 로그 설정
logging:
  level:
    com.backend: DEBUG # 우리 패키지는 DEBUG 레벨
    org.hibernate.SQL: DEBUG # SQL 쿼리 로그
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE # SQL 파라미터 로그
    org.springframework.web: DEBUG # 웹 요청 로그
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# 프로메테우스 관련 설정
management:
  endpoints:
    web:
      exposure:
        include: "prometheus, health"
  endpoint:
    health:
      show-details: always

# 이미지 업로드 설정
app:
  upload:
    prefix: images
  cdn:
    domain: https://dke56if5x4hny.cloudfront.net
