# import external config
# 외부 환경 변수 로드
spring:
  config:
    import:
      - aws-parameterstore:/ourhour/

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}

  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true

  # 메일 설정
  mail:
    from: ${mail.from}
    host: smtp.gmail.com
    port: 587
    username: ${mail.username}
    password: ${mail.password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  service:
    url:
      front: ${url.front}
    base-url-email: http://localhost:8080

# AWS 설정 (지역 및 인증 프로파일)
cloud:
  aws:
    region:
      static: ap-northeast-2
    credentials:
      profile:
        name: default 


# 이미지 업로드 설정
app:
  upload:
    path: ./uploads/images

  web:
    resources:
      static-locations: classpath:/static/,file:uploads/images/

# 로그 설정
logging:
  level:
    com.backend: DEBUG # 우리 패키지는 DEBUG 레벨
    org.hibernate.SQL: DEBUG # SQL 쿼리 로그
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE # SQL 파라미터 로그
    org.springframework.web: DEBUG # 웹 요청 로그
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# JWT 관련 설정
jwt:
  secret: ${jwt.secret} 
  access-token-validity-in-seconds: ${jwt.access-token}
  refresh-token-validity-in-seconds: ${jwt.refresh-token}

