spring:
  # DB 관련 설정
  datasource:
    url: ${DB_URL}?serverTimezone=Asia/Seoul
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  # 메일 관련 설정
  mail:
    from: ${MAIL_FROM}
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  # 프론트엔드 관련 설정
  service:
    url:
      front: ${FRONTEND_URL}

  # AWS 설정 (지역 및 인증 프로파일)
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID}
        secret-key: ${AWS_SECRET_ACCESS_KEY}
      region:
        static: ${AWS_REGION}
      s3:
        bucket: ${AWS_S3_BUCKET_NAME}
      stack:
        auto: false

  # Redis 설정
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      timeout: 2000ms
      database: 0
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 1
          time-between-eviction-runs: 30s

  # 캐시 설정
  cache:
    type: redis
    redis:
      time-to-live: 3600000  # 1시간 (밀리초)
      cache-null-values: false

# JWT 관련 설정
jwt:
  secret: ${JWT_SECRET}
  access-token-validity-in-seconds: ${JWT_ACCESS}
  refresh-token-validity-in-seconds: ${JWT_REFRESH}

# Cookie 관련 설정
cookie:
  secure: ${COOKIE_SECURE}
  same-site: ${COOKIE_SAMESITE}

# 암호화 설정
encryption:
  secret-key: ${ENCRYPTION_SECRET_KEY}

# GitHub OAuth 설정
github:
  client-id: ${APPLICATION_GITHUB_CLIENT_ID}
  client-secret: ${APPLICATION_GITHUB_CLIENT_SECRET}
  redirect-uri: ${APPLICATION_GITHUB_REDIRECT_URI}
  scope: ${APPLICATION_GITHUB_SCOPE}

# 소셜 로그인 OAuth 설정
signin:
  github:
    client-id: ${SIGNIN_GITHUB_CLIENT_ID}
    client-secret: ${SIGNIN_GITHUB_CLIENT_SECRET}
  google:
    client-id: ${SIGNIN_GOOGLE_CLIENT_ID}
    client-secret: ${SIGNIN_GOOGLE_CLIENT_SECRET}
  redirect-uri: ${SIGNIN_REDIRECT_URI}

# 이미지 캐시 관련 설정
app:
  cdn:
    domain: ${CDN_DOMAIN}
  upload:
    prefix: ${UPLOAD_PREFIX:images}
  cache:
    image:
      ttl: 3600  # 1시간 (초)
      max-size: 100  # 최대 캐시 항목 수
    presign:
      ttl: 600   # 10분 (초)

# 프로메테우스 관련 설정
management:
  endpoints:
    web:
      exposure:
        include: "prometheus, health"
  endpoint:
    health:
      show-details: always

# LLM fast api 서버
python-server:
  url: ${PYTHON_SERVER_URL:http://localhost:8000}