name: CI-CD

on:
  push:
    branches: ["main", "release", "test"]
  pull_request:
    branches: ["develop", "main", "release"]

jobs:
  #-------------------------CI-------------------------
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      # Backend 빌드
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      # gradle 캐시
      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # python(pip) 캐시
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set execute permission on gradlew
        run: chmod +x ./gradlew
        working-directory: ./backend

      # test
      - name: Run Tests with Gradle
        run: ./gradlew test --no-daemon
        working-directory: ./backend

      # test 제외 build
      - name: Build JAR for Deployment
        run: ./gradlew clean bootJar --no-daemon
        working-directory: ./backend

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-jar
          path: ./backend/build/libs/backend-0.0.1-SNAPSHOT.jar

      # Frontend 코드 품질 검사 (Vercel 배포 전 검증용)
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: "./frontend/package-lock.json"

      - name: Install dependencies
        run: npm ci
        working-directory: ./frontend

      - name: Run code quality checks
        run: |
          npm run lint &
          npm run format:check &
          wait
        working-directory: ./frontend

      - name: Run tests
        run: npm run coverage
        working-directory: ./frontend

  #-------------------------CD-------------------------
  # Docker 이미지 빌드 및 푸시
  build-docker:
    needs: build-test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/release' || github.ref == 'refs/heads/main' || github.ref == 'refs/heads/test')

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-jar
          path: ./backend/build/libs/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Generate image tags (docker job)
        id: image-tags
        run: |
          if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
            echo "backend=ourhour-backend:release-${GITHUB_SHA}" >> "$GITHUB_OUTPUT"
            echo "chatbot=ourhour-chatbot:release-${GITHUB_SHA}" >> "$GITHUB_OUTPUT"
          elif [[ "${GITHUB_REF}" == "refs/heads/release" ]]; then
            echo "backend=ourhour-backend:test-${GITHUB_SHA}" >> "$GITHUB_OUTPUT"
            echo "chatbot=ourhour-chatbot:test-${GITHUB_SHA}" >> "$GITHUB_OUTPUT"
          elif [[ "${GITHUB_REF}" == "refs/heads/test" ]]; then
            echo "backend=ourhour-backend:test-${GITHUB_SHA}" >> "$GITHUB_OUTPUT"
          fi

      - name: Build and push Backend Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          target: release
          push: true
          tags: ${{ (secrets.DOCKER_USERNAME != '' && format('{0}/{1}', secrets.DOCKER_USERNAME, steps['image-tags'].outputs.backend)) || format('myuser/{0}', steps['image-tags'].outputs.backend) }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

#      - name: Build and push Chatbot Docker image
#        uses: docker/build-push-action@v5
#        with:
#          context: ./llm
#          push: true
#          tags: ${{ (secrets.DOCKER_USERNAME != '' && format('{0}/{1}', secrets.DOCKER_USERNAME, steps['image-tags'].outputs.chatbot)) || format('myuser/{0}', steps['image-tags'].outputs.chatbot) }}
#          cache-from: type=gha
#          cache-to: type=gha,mode=max

  # 배포 태스트용 (release 브랜치) - AWS
  deploy-docker-test-aws:
    needs: [build-test, build-docker]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/test' && github.event_name == 'push'
    environment: development

    # 백엔드, db, redis
    steps:
      - name: Deploy with Docker to test on aws
        timeout-minutes: 30
        uses: appleboy/ssh-action@v1.0.3
        continue-on-error: true
        with:
          host: ${{ secrets.PROD_EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          command_timeout: 1h
          script: |
            cd /home/ubuntu/ourHour

            # 최신 release 브랜치 pull
            git fetch origin
            git checkout test
            git reset --hard origin/test

            echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

            docker compose down -p ourhour-test || true            
            
            # 환경 변수 세팅
            ./generate-env.sh test aws > .env
            
            # 백엔드 이미지 pull
            docker pull ${{ secrets.DOCKER_USERNAME }}/ourhour-backend:test-${{ github.sha }}
            export BACKEND_IMAGE=${{ secrets.DOCKER_USERNAME }}/ourhour-backend:test-${{ github.sha }}
            
            docker compose --profile aws -p ourhour-test up -d

            docker image prune -f

#  # 배포 태스트용 (release 브랜치) - GCP
#  deploy-docker-test-gcp:
#    needs: [ build-test, build-docker ]
#    runs-on: ubuntu-latest
#    if: github.ref == 'refs/heads/release' && github.event_name == 'push'
#    environment: development
#
#    # GCP(llm)
#    steps:
#      - name: Deploy with Docker to test on gcp
#        timeout-minutes: 30
#        uses: appleboy/ssh-action@v1.0.3
#        continue-on-error: true
#        with:
#          host: ${{ secrets.PROD_VM_HOST }}
#          username: ${{ secrets.VM_USERNAME }}
#          key: ${{ secrets.VM_PRIVATE_KEY }}
#          command_timeout: 1h
#          script: |
#            cd /home/ubuntu/ourHour
#
#            # 최신 release 브랜치 pull
#            git fetch origin
#            git checkout release
#            git reset --hard origin/release
#
#            echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
#
#            docker compose down -p ourhour-test || true
#
#            # 환경 변수 세팅
#            ./generate-env.sh test gcp > .env
#
#            docker pull ${{ secrets.DOCKER_USERNAME }}/ourhour-chatbot:test-${{ github.sha }}
#            export CHATBOT_IMAGE=${{ secrets.DOCKER_USERNAME }}/ourhour-chatbot:test-${{ github.sha }}
#
#            docker compose --profile gcp -p ourhour-test up -d
#
#            docker image prune -f

  # 배포용 Docker (main 브랜치)
  deploy-docker-prod:
    needs: [build-test, build-docker]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    environment: production

    steps:
      - name: Deploy with Docker to Production
        timeout-minutes: 30
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PROD_EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          command_timeout: 1h
          script: |
            # 애플리케이션 디렉토리로 이동
            cd /home/ubuntu/ourHour

            # 최신 release 브랜치 pull
            git fetch origin
            git checkout test
            git reset --hard origin/test

            # Docker 로그인
            echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

            # 기존 컨테이너 중지 및 제거
            docker compose -f docker-compose.yml -f docker-compose.release.yml down -p ourhour-release || true

            # 최신 이미지 풀
            docker pull ${{ secrets.DOCKER_USERNAME }}/ourhour-backend:prod-${{ github.sha }}
            docker pull ${{ secrets.DOCKER_USERNAME }}/ourhour-chatbot:prod-${{ github.sha }}

            export BACKEND_IMAGE=${{ secrets.DOCKER_USERNAME }}/ourhour-backend:prod-${{ github.sha }}
            export CHATBOT_IMAGE=${{ secrets.DOCKER_USERNAME }}/ourhour-chatbot:prod-${{ github.sha }}

            # Redis 환경변수를 AWS Parameter Store에서 가져오기
            export REDIS_HOST=$(aws ssm get-parameter --name "/ourhour/release/redis/host" --with-decryption --query 'Parameter.Value' --output text --region ap-northeast-2)
            export REDIS_PORT=$(aws ssm get-parameter --name "/ourhour/release/redis/port" --with-decryption --query 'Parameter.Value' --output text --region ap-northeast-2)
            export REDIS_PASSWORD=$(aws ssm get-parameter --name "/ourhour/release/redis/password" --with-decryption --query 'Parameter.Value' --output text --region ap-northeast-2)

            # chatbot 환경변수
            export OPENAI_API_KEY=$(aws ssm get-parameter --name "/ourhour/llm/openai-api-key" --with-decryption --query 'Parameter.Value' --output text --region ap-northeast-2)
            export CHATBOT_DATABASE_URL=$(aws ssm get-parameter --name "/ourhour/release/llm/chatbot-db" --with-decryption --query 'Parameter.Value' --output text --region ap-northeast-2)
            export OURHOUR_API_URL=$(aws ssm get-parameter --name "/ourhour/release/llm/ourhour-api/url" --with-decryption --query 'Parameter.Value' --output text --region ap-northeast-2)
            export PINECONE_API_KEY=$(aws ssm get-parameter --name "/ourhour/llm/pinecone-api-key" --with-decryption --query 'Parameter.Value' --output text --region ap-northeast-2)
            export PINECONE_INDEX_NAME=$(aws ssm get-parameter --name "/ourhour/llm/pinecone-index-name" --with-decryption --query 'Parameter.Value' --output text --region ap-northeast-2)
            export PINECONE_ENVIRONMENT=$(aws ssm get-parameter --name "/ourhour/llm/pinecone-environment" --with-decryption --query 'Parameter.Value' --output text --region ap-northeast-2)
            export JWT_SECRET=$(aws ssm get-parameter --name "/ourhour/release/jwt/secret" --with-decryption --query 'Parameter.Value' --output text --region ap-northeast-2)
          
            # DB init parameter
            export MYSQL_ROOT_PASSWORD=$(aws ssm get-parameter --name "/ourhour/db/root-password" --with-decryption --query 'Parameter.Value' --output text --region ap-northeast-2)
            export MYSQL_DATABASE=$(aws ssm get-parameter --name "/ourhour/release/db" --with-decryption --query 'Parameter.Value' --output text --region ap-northeast-2)
            export MYSQL_USER=$(aws ssm get-parameter --name "/ourhour/release/db/username" --with-decryption --query 'Parameter.Value' --output text --region ap-northeast-2)
            export MYSQL_PASSWORD=$(aws ssm get-parameter --name "/ourhour/release/db/password" --with-decryption --query 'Parameter.Value' --output text --region ap-northeast-2)

            # 새 컨테이너 시작 (AWS Parameter Store에서 환경변수 자동 로드)
            docker compose -f docker-compose.yml -f docker-compose.release.yml -p ourhour-release up -d

            # 불필요한 이미지 정리
            docker image prune -f
