name: CI-CD

on:
  push:
    branches: ["develop", "main", "release"]
  pull_request:
    branches: ["develop", "main", "release"]

jobs:
  #-------------------------CI-------------------------
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      # Backend 빌드
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set execute permission on gradlew
        run: chmod +x ./gradlew
        working-directory: ./backend

      # 개발 환경용 환경 변수 세팅
      - name: Set environment variables for dev
        if: github.ref == 'refs/heads/develop'
        run: |
          echo "SPRING_PROFILES_ACTIVE=dev" >> $GITHUB_ENV
          echo "DB_URL=${{ secrets.DEV_DB_URL }}" >> $GITHUB_ENV
          echo "DB_USERNAME=${{ secrets.DEV_DB_USERNAME }}" >> $GITHUB_ENV
          echo "DB_PASSWORD=${{ secrets.DEV_DB_PASSWORD }}" >> $GITHUB_ENV
          echo "MAIL_FROM=${{ secrets.MAIL_FROM }}" >> $GITHUB_ENV
          echo "MAIL_USERNAME=${{ secrets.MAIL_USERNAME }}" >> $GITHUB_ENV
          echo "MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}" >> $GITHUB_ENV
          echo "FRONTEND_URL=${{ secrets.FRONTEND_URL }}" >> $GITHUB_ENV
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> $GITHUB_ENV
          echo "JWT_ACCESS=${{ secrets.JWT_ACCESS }}" >> $GITHUB_ENV
          echo "JWT_REFRESH=${{ secrets.JWT_REFRESH }}" >> $GITHUB_ENV
          echo "ENCRYPTION_SECRET_KEY=${{ secrets.ENCRYPTION_SECRET_KEY }}" >> $GITHUB_ENV
          echo "APPLICATION_GITHUB_CLIENT_ID=${{ secrets.APPLICATION_GITHUB_CLIENT_ID }}" >> $GITHUB_ENV
          echo "APPLICATION_GITHUB_CLIENT_SECRET=${{ secrets.APPLICATION_GITHUB_CLIENT_SECRET }}" >> $GITHUB_ENV
          echo "APPLICATION_GITHUB_REDIRECT_URI=${{ secrets.APPLICATION_GITHUB_REDIRECT_URI }}" >> $GITHUB_ENV
          echo "APPLICATION_GITHUB_SCOPE=${{ secrets.APPLICATION_GITHUB_SCOPE }}" >> $GITHUB_ENV

      # test
      - name: Run Tests with Gradle
        run: ./gradlew test --no-daemon
        working-directory: ./backend

      # test 제외 build
      - name: Build JAR for Deployment
        run: ./gradlew clean bootJar --no-daemon
        working-directory: ./backend

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-jar
          path: ./backend/build/libs/backend-0.0.1-SNAPSHOT.jar

      # Frontend 코드 품질 검사 (Vercel 배포 전 검증용)
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: "./frontend/package-lock.json"

      - name: Install dependencies
        run: npm ci
        working-directory: ./frontend

      - name: Run code quality checks
        run: |
          npm run lint &
          npm run format:check &
          wait
        working-directory: ./frontend

      - name: Run tests
        run: npm run coverage
        working-directory: ./frontend

      # python(pip) 캐시
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

  #-------------------------CD-------------------------
  # Docker 이미지 빌드 및 푸시
  build-docker:
    needs: build-test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/release' || github.ref == 'refs/heads/main')

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-jar
          path: ./backend/build/libs/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Generate image tags (docker job)
        id: image-tags
        run: |
          if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
            echo "backend=ourhour-backend:prod-${GITHUB_SHA}" >> "$GITHUB_OUTPUT"
            echo "chatbot=ourhour-chatbot:prod-latest" >> "$GITHUB_OUTPUT"
          elif [[ "${GITHUB_REF}" == "refs/heads/release" ]]; then
            echo "backend=ourhour-backend:test-${GITHUB_SHA}" >> "$GITHUB_OUTPUT"
            echo "chatbot=ourhour-chatbot:prod-${GITHUB_SHA}" >> "$GITHUB_OUTPUT"
          fi

      - name: Build and push Backend Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          target: release
          push: true
          tags: ${{ (secrets.DOCKER_USERNAME != '' && format('{0}/{1}', secrets.DOCKER_USERNAME, steps['image-tags'].outputs.backend)) || format('myuser/{0}', steps['image-tags'].outputs.backend) }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # 배포 태스트용 Docker (release 브랜치)
  deploy-docker-test:
    needs: [build-test, build-docker]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/release' && github.event_name == 'push'
    environment: development

    steps:
      - name: Deploy with Docker to test
        timeout-minutes: 30
        uses: appleboy/ssh-action@v1.0.3
        continue-on-error: true
        with:
          host: ${{ secrets.PROD_EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          command_timeout: 1h
          script: |
            cd /home/ubuntu/ourHour

            echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

            docker compose -f docker-compose.yml -f docker-compose.test.yml down -p ourhour-test || true            

            docker pull ${{ secrets.DOCKER_USERNAME }}/ourhour-backend:test-${{ github.sha }}

            export BACKEND_IMAGE=${{ secrets.DOCKER_USERNAME }}/ourhour-backend:test-${{ github.sha }}

            # Redis 환경변수를 AWS Parameter Store에서 가져오기
            export REDIS_HOST=$(aws ssm get-parameter --name "/ourhour/test/redis/host" --with-decryption --query 'Parameter.Value' --output text --region ap-northeast-2)
            export REDIS_PORT=$(aws ssm get-parameter --name "/ourhour/test/redis/port" --with-decryption --query 'Parameter.Value' --output text --region ap-northeast-2)
            export REDIS_PASSWORD=$(aws ssm get-parameter --name "/ourhour/test/redis/password" --with-decryption --query 'Parameter.Value' --output text --region ap-northeast-2)

            # chatbot 환경변수
            export PYTHON_SERVER_URL=$(aws ssm get-parameter --name "/ourhour/test/python-server/url" --with-decryption --query 'Parameter.Value' --output text --region ap-northeast-2)
            export OURHOUR_API_URL=$(aws ssm get-parameter --name "/ourhour/test/ourhour-api/url" --with-decryption --query 'Parameter.Value' --output text --region ap-northeast-2)
            export OPENAI_API_KEY=$(aws ssm get-parameter --name "/ourhour/test/openai/api-key" --with-decryption --query 'Parameter.Value' --output text --region ap-northeast-2)

            # DB init parameter
            export MYSQL_ROOT_PASSWORD=$(aws ssm get-parameter --name "/ourhour/db/root-password" --with-decryption --query 'Parameter.Value' --output text --region ap-northeast-2)
            export MYSQL_DATABASE=$(aws ssm get-parameter --name "/ourhour/test/db" --with-decryption --query 'Parameter.Value' --output text --region ap-northeast-2)
            export MYSQL_USER=$(aws ssm get-parameter --name "/ourhour/test/db/username" --with-decryption --query 'Parameter.Value' --output text --region ap-northeast-2)
            export MYSQL_PASSWORD=$(aws ssm get-parameter --name "/ourhour/test/db/password" --with-decryption --query 'Parameter.Value' --output text --region ap-northeast-2)

            export BACKEND_PORT=8081
                        
            docker compose -f docker-compose.yml -f docker-compose.test.yml -p ourhour-test up -d

            docker image prune -f

  # 배포용 Docker (main 브랜치)
  deploy-docker-prod:
    needs: [build-test, build-docker]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/release' && github.event_name == 'push'
    environment: production

    steps:
      - name: Deploy with Docker to Production
        timeout-minutes: 30
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PROD_EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          command_timeout: 1h
          script: |
            # 애플리케이션 디렉토리로 이동
            cd /home/ubuntu/ourHour
            
            # Docker 로그인
            echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

            # 기존 컨테이너 중지 및 제거
            docker compose -f docker-compose.yml -f docker-compose.release.yml down -p ourhour-release || true

            # 최신 이미지 풀
            docker pull ${{ secrets.DOCKER_USERNAME }}/ourhour-backend:prod-${{ github.sha }}
            export CHATBOT_IMAGE=${{ secrets.DOCKER_USERNAME }}/ourhour-chatbot:prod-latest

            export BACKEND_IMAGE=${{ secrets.DOCKER_USERNAME }}/ourhour-backend:prod-${{ github.sha }}

            # Redis 환경변수를 AWS Parameter Store에서 가져오기
            export REDIS_HOST=$(aws ssm get-parameter --name "/ourhour/release/redis/host" --with-decryption --query 'Parameter.Value' --output text --region ap-northeast-2)
            export REDIS_PORT=$(aws ssm get-parameter --name "/ourhour/release/redis/port" --with-decryption --query 'Parameter.Value' --output text --region ap-northeast-2)
            export REDIS_PASSWORD=$(aws ssm get-parameter --name "/ourhour/release/redis/password" --with-decryption --query 'Parameter.Value' --output text --region ap-northeast-2)

            # chatbot 환경변수
            export PYTHON_SERVER_URL=$(aws ssm get-parameter --name "/ourhour/release/python-server/url" --with-decryption --query 'Parameter.Value' --output text --region ap-northeast-2)
            export OURHOUR_API_URL=$(aws ssm get-parameter --name "/ourhour/release/ourhour-api/url" --with-decryption --query 'Parameter.Value' --output text --region ap-northeast-2)
            export OPENAI_API_KEY=$(aws ssm get-parameter --name "/ourhour/release/openai/api-key" --with-decryption --query 'Parameter.Value' --output text --region ap-northeast-2)

            # DB init parameter
            export MYSQL_ROOT_PASSWORD=$(aws ssm get-parameter --name "/ourhour/db/root-password" --with-decryption --query 'Parameter.Value' --output text --region ap-northeast-2)
            export MYSQL_DATABASE=$(aws ssm get-parameter --name "/ourhour/release/db" --with-decryption --query 'Parameter.Value' --output text --region ap-northeast-2)
            export MYSQL_USER=$(aws ssm get-parameter --name "/ourhour/release/db/username" --with-decryption --query 'Parameter.Value' --output text --region ap-northeast-2)
            export MYSQL_PASSWORD=$(aws ssm get-parameter --name "/ourhour/release/db/password" --with-decryption --query 'Parameter.Value' --output text --region ap-northeast-2)

            # 새 컨테이너 시작 (AWS Parameter Store에서 환경변수 자동 로드)
            docker compose -f docker-compose.yml -f docker-compose.release.yml -p ourhour-release up -d

            # 불필요한 이미지 정리
            docker image prune -f