name: CI-CD

on:
  push:
    branches: ["main", "release"]
  pull_request:
    branches: ["develop", "main", "release"]

jobs:
  #-------------------------CI-------------------------
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      # Backend 빌드
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      # gradle 캐시
      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # python(pip) 캐시
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set execute permission on gradlew
        run: chmod +x ./gradlew
        working-directory: ./backend

      # test
      - name: Run Tests with Gradle
        run: ./gradlew test --no-daemon
        working-directory: ./backend

      # test 제외 build
      - name: Build JAR for Deployment
        run: ./gradlew clean bootJar --no-daemon
        working-directory: ./backend

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-jar
          path: ./backend/build/libs/backend-0.0.1-SNAPSHOT.jar

      # Frontend 코드 품질 검사 (Vercel 배포 전 검증용)
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: "./frontend/package-lock.json"

      - name: Install dependencies
        run: npm ci
        working-directory: ./frontend

      - name: Run code quality checks
        run: |
          npm run lint &
          npm run format:check &
          wait
        working-directory: ./frontend

      - name: Run tests
        run: npm run coverage
        working-directory: ./frontend

  #-------------------------CD-------------------------
  # Docker 이미지 빌드 및 푸시
  build-docker:
    needs: build-test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/release' || github.ref == 'refs/heads/main')

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-jar
          path: ./backend/build/libs/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Generate image tags (docker job)
        id: image-tags
        run: |
          if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
            echo "backend=ourhour-backend:release-${GITHUB_SHA}" >> "$GITHUB_OUTPUT"
          elif [[ "${GITHUB_REF}" == "refs/heads/release" ]]; then
            echo "backend=ourhour-backend:test-${GITHUB_SHA}" >> "$GITHUB_OUTPUT"
          fi

      - name: Build and push Backend Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          target: release
          push: true
          tags: ${{ (secrets.DOCKER_USERNAME != '' && format('{0}/{1}', secrets.DOCKER_USERNAME, steps['image-tags'].outputs.backend)) || format('myuser/{0}', steps['image-tags'].outputs.backend) }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # 배포 태스트용 (release 브랜치) - AWS
  deploy-docker-test:
    needs: [build-test, build-docker]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/release' && github.event_name == 'push'
    environment: development

    # 백엔드, db, redis
    steps:
      - name: Deploy with Docker to test
        timeout-minutes: 30
        uses: appleboy/ssh-action@v1.0.3
        continue-on-error: true
        with:
          host: ${{ secrets.PROD_EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          command_timeout: 1h
          script: |
            cd /home/ubuntu/ourHour

            # 최신 release 브랜치 pull
            git fetch origin
            git checkout release
            git reset --hard origin/release

            echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

            docker compose down -p ourhour-test || true            
            
            # 환경 변수 세팅
            chmod +x ./generate-env.sh
            ./generate-env.sh test 
            
            # 백엔드 이미지 pull
            docker pull ${{ secrets.DOCKER_USERNAME }}/ourhour-backend:test-${{ github.sha }}
            export BACKEND_IMAGE=${{ secrets.DOCKER_USERNAME }}/ourhour-backend:test-${{ github.sha }}
            
            docker compose -p ourhour-test up -d

            docker image prune -f

  # 배포용 Docker (main 브랜치)
  deploy-docker-release:
    needs: [build-test, build-docker]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    environment: production

    steps:
      - name: Deploy with Docker to Production
        timeout-minutes: 30
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PROD_EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          command_timeout: 1h
          script: |
            # 애플리케이션 디렉토리로 이동
            cd /home/ubuntu/ourHour

            # 최신 main 브랜치 pull
            git fetch origin
            git checkout main
            git reset --hard origin/main

            # Docker 로그인
            echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

            # 기존 컨테이너 중지 및 제거
            docker compose down -p ourhour-release || true
            
            # 환경 변수 세팅
            chmod +x ./generate-env.sh
            ./generate-env.sh release 

            # 백엔드 이미지 풀
            docker pull ${{ secrets.DOCKER_USERNAME }}/ourhour-backend:release-${{ github.sha }}
            export BACKEND_IMAGE=${{ secrets.DOCKER_USERNAME }}/ourhour-backend:release-${{ github.sha }}

            # 새 컨테이너 시작 
            docker compose -p ourhour-release up -d

            # 불필요한 이미지 정리
            docker image prune -f
